security:
    #  C칩mo se guardan las contrase침as
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    #   D칩nde est치n los usuarios (Base de Datos)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    #  CORTAFUEGOS: 
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

             Login con formulario
            form_login:
                login_path: app_login 
                check_path: app_login 
                enable_csrf: true      
                default_target_path: app_home 

            #  Logout
            logout:
                path: app_logout
                target: app_login

    #  CONTROL DE ACCESO
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }